### ISSUE TITLE
Bedmaster time zigzag

### ISSUE THREAD

**Issue by StevenSong** [aguirre-lab/ml4c3#1308]
within a single `.mat` file, there are jumps back in time and timestamps are repeated

its still 1000ish minutes of data

![image](https://user-images.githubusercontent.com/26208374/106929071-e9bbb600-66e1-11eb-860d-f1ff579bb186.png)

**Comment by StevenSong** [comment]
there's 14 occurrences of the end time being earlier than the start time. however this is not necessarily enough to say that these large jumps back in time _within_ a .mat file, are not more prevalent. to truly find these, we'd need to scan the entire time array of every file, a very expensive task...

**Comment by StevenSong** [comment]
@wolfgang-ganglberger @contactadityag @matt-cdac @aguirre-lab/ml4c3-dev thoughts? especially on trying to quantify how prevalent these zigzags are?

**Comment by StevenSong** [comment]
quick test of #1309 showed it would be far too slow
#1310 does not solve this but it throws out the obviously wrong files (the ones with time jumps back so far that the end time is before the start time)

**Comment by wolfgang-ganglberger** [comment]
Hi Steven, huh. 
First though, it is still possible that there are time monotonicity breaks in the files. We have encountered one issue that we could not logically solve, those are the ones marked as dataevent==5, see https://github.com/aguirre-lab/ml4c3/wiki/Bedmaster-irregularities.
Could you check if those non-monotonicities are in fact labeled as dataevent 5? if they are, i think this is unfortunately the case for some of the bedmaster files, hopefully a very small number.

If no, it means there's some property/behavior in this file that yuping and I did not observe when we did our iterative time-fixing development.

**Comment by StevenSong** [comment]
@wolfgang-ganglberger it seems like these are data event 5, orange bars are where those events are recorded:
![image](https://user-images.githubusercontent.com/26208374/106951670-0c5bc800-66fe-11eb-86ed-f8ffe85fa0b9.png)

i dont understand how it could result in such a drastic jump back though, this is not on the order of 5 seconds but more like 25,000 seconds

**Comment by RidwanAlam** [comment]
@wolfgang-ganglberger Thanks for your input. 
From your experience (though you mentioned it's been a while), do you remember seeing anything like this? More precisely, can you atleast comment on whether this is an issue worth spending efforts?
If it's a prevalent case, you can dig into Yuping's code base to see what was causing this behavior. 
@erikr and @StevenSong we have access to that code base, right?

**Comment by RidwanAlam** [comment]
> i dont understand how it could result in such a drastic jump back though, this is not on the order of 5 seconds but more like 25,000 seconds

just wondering, if this single `mat` file belongs to a single patient or multiple patients? How can a single patient have multiple data points from same time?

**Comment by wolfgang-ganglberger** [comment]
@StevenSong @RidwanAlam I'm not sure if we have seen such an extreme case in our development phase but we did see a patient that also had a huge data event 5 jump. The underlying .xml file (stp->.xml->.mat) was highly highly unusable, i.e. a lot of weird and missing info. 

I think it's possible to get you the .xml file in case you want to have a look (@matt-cdac) but my personal opinion is those patients/files are unusable.

**Comment by erikr** [comment]
> @erikr and @StevenSong we have access to that code base, right?

That is a question for @wolfgang-ganglberger @matt-cdac @contactadityag

**Comment by erikr** [comment]
@StevenSong @RidwanAlam @epalto should this be addressed by a QC step during tensorization?

**Comment by epalto** [comment]
We can quantify the problem by getting the amount of patients that have at least one dataevent 5. This wouldn't be too expensive to run. According to some statistics I did last summer, datavents were really rare: 4.52e-7% (https://github.com/aguirre-lab/ml4c3/wiki/Bedmaster-statistics). We could rerun this analysis to make sure it's that rare, but if that's the case we could remove all patients that contain at least one dataevent 5

**Comment by RidwanAlam** [comment]
> We can quantify the problem by getting the amount of patients that have at least one dataevent 5. This wouldn't be too expensive to run. According to some statistics I did last summer, datavents were really rare: 4.52e-7% (https://github.com/aguirre-lab/ml4c3/wiki/Bedmaster-statistics). We could rerun this analysis to make sure it's that rare, but if that's the case we could remove all patients that contain at least one dataevent 5

that's good to know. instead of removing the patient, what about the `bedmaster_indexer` raise a flag for the `mat` files that contain `data event 5`. and the `xref` or `writer` ignores those `mat` files totally (i.e. doesn't take anything from those "flagged" `mat` files). thoughts?

**Comment by RidwanAlam** [comment]
> @StevenSong @RidwanAlam I'm not sure if we have seen such an extreme case in our development phase but we did see a patient that also had a huge data event 5 jump. The underlying .xml file (stp->.xml->.mat) was highly highly unusable, i.e. a lot of weird and missing info.
> 
> I think it's possible to get you the .xml file in case you want to have a look (@matt-cdac) but my personal opinion is those patients/files are unusable.

thanks @wolfgang-ganglberger and @epalto. truly appreciate your experienced opinion. 
i also don't prefer to re-invent the wheel from the `stp` files, would rather listen to your guidance.
for smaller cohorts, removing a patient may not be a good idea; 
what would be the drawback of removing only the `mat` file instead of the `mrn`?

**Comment by RidwanAlam** [comment]
> > i dont understand how it could result in such a drastic jump back though, this is not on the order of 5 seconds but more like 25,000 seconds
 
> just wondering, if this single `mat` file belongs to a single patient or multiple patients? How can a single patient have multiple data points from same time?

**Comment by RidwanAlam** [comment]
> @StevenSong @RidwanAlam @epalto should this be addressed by a QC step that checks for jumps back within a mat file during tensorization, and if a sufficient number of sufficiently large jump is identified, that patient is marked as "bad" and no hd5 is produced? Or, we tensorize it but the log file indicates the bad files?

indeed @erikr . I believe what @StevenSong is trying to achieve here, which I strongly support, is to make as minimum assumptions about the data as possible. 
hopefully the bedmaster_indexer will be able to get rid of most of the assumptions, such as whether any jump is due to `transferOut` vs `data event 5`, and then the QC would be much more helpful.

**Comment by matt-cdac** [comment]
Hi All, we have Yu-Ping's code in github if you'd like to read through it. It's a private repo but I can grant read access to others. This particular file was converted in March, so we do not have its XML available but we could generate it by re-converting the original STP if that would be helpful.

**Comment by StevenSong** [comment]
> what about the `bedmaster_indexer` raise a flag for the `mat` files that contain `data event 5`

I think the indexer, the cross referencer, and the tensorizer accomplish 3 distinct tasks that all feed into each other
- the indexer simply gets metadata that doesnt require heavy reading of the data (a job accomplished by the tensorizer)
- the cross referencer compares the index with some ADT and gets a list of all possible matches for `.mat` files
- the tensorizer reads and writes data but most importantly, it is the one which reads all the data and can best discern "does this file contain data event 5" (as the data events are encoded as boolean vectors equal in length to the time array)



> should this be addressed by a QC step that checks for jumps back within a mat file during tensorization, and if a sufficient number of sufficiently large jump is identified, that patient is marked as "bad" and no hd5 is produced? Or, we tensorize it but the log file indicates the bad files?

I think tensorizer, while reading each file, if it identifies a sufficiently large data event 5 or perhaps even any data event 5, then we throw out that single `.mat` file? I wonder do data event 5 have compounding effects in downstream `.mat` files which otherwise appear correct? @wolfgang-ganglberger @epalto 

@matt-cdac if you could add me, I'd be interested in taking a quick look

**Comment by RidwanAlam** [comment]
> I think tensorizer, while reading each file, if it identifies a sufficiently large data event 5 or perhaps even any data event 5, then we throw out that single `.mat` file? 
Great! and thanks for the explanation.

> I wonder do data event 5 have compounding effects in downstream `.mat` files which otherwise appear correct? @wolfgang-ganglberger @epalto 
that's my question too.

> @matt-cdac if you could add me, I'd be interested in taking a quick look
@matt-cdac please add me too. thanks.

**Comment by matt-cdac** [comment]
Sent invites to @RidwanAlam & @StevenSong. Will send an email pointing them to the conversion files

**Comment by StevenSong** [comment]
Thank you @matt-cdac!



> I wonder do data event 5 have compounding effects in downstream `.mat` files which otherwise appear correct? @wolfgang-ganglberger @epalto

within our tensorization process (downstream of potential propagation within `.mat` files), interbundle corrections would probably propagate some error due to an extreme case of data event 5 like we see in this issue: https://github.com/aguirre-lab/ml4c3/wiki/Bedmaster-irregularities#inter-bundle-correction

**Comment by epalto** [comment]
Right @StevenSong , there may be issues with the interbundle correction and dataevent 5. 

Some are easy to fix on the tensorizer, since the interbundle correction is calculated when reading the files, not when writing them. In case we decide not to write `.mat` files with dataevent 5, we could still read them in order to mind them for the  interbundle correction.

I'm concerned about the timespans after the dataevent 5, though. For instance, in the image posted above:
![image](https://user-images.githubusercontent.com/61511203/107064880-10452400-67aa-11eb-977d-b601ce6d855c.png)

If we don't write this `.mat` file but we write the next one, and that file starts as a normal monotonous continuation of the last timespans, we will be generating a non-monotonicity between the last timestamp of the previous file and the first timestamp of the next `.mat` file.  

![Screenshot from 2021-02-05 12-15-42](https://user-images.githubusercontent.com/61511203/107066420-f4428200-67ab-11eb-83f1-74649b70e7a9.png)

If we use  `.mat` files with dataevent 5 for the interbundle correction, it won't fix the issue because it won't find any discrepancy between the last timestamps of the incorrect file and the first timestamps of the next one. If we completely ignore the incorrect files for interbundle correction, then it will align the timespans of the next file so that they are a continuation of the values of the previous file, but this seems artificial.  

So I can think of three options: 
* We write all the `.mat` files and we let the user decide what to do with data containing dataevent 5 by looking at the `time_corr_array`.
* We don't write any `.mat` file after the first appearance of a dataevent 5
* We do some check on the next `.mat` file timestamps

**Comment by wolfgang-ganglberger** [comment]
Hi guys,
haha that's awesome, truly appreciate your eagerness, I wish you guys were onboard a year ago!

I believe the dataevent 5 causes potential issues until the next dataevent 1 (https://github.com/aguirre-lab/ml4c3/wiki/Bedmaster-irregularities). because by definition, the dataevent 1 uses the original/non-corrected timestamp again. 
this is the 'technical answer'.

why those dataevent 5 instances occur in the first place and if this indicates a larger problem in the overall recording, I do not know. In case the patient you found has a data event 1 appearing after, you could plot the bedmaster-vitals next to the EDW-vitals and see if they a) are not aligned until/around dataevent 5, b) are aligned again after dataevent 5.

Further, I of course agree with the statement removing an MRN fully based on a single dataevent 5 is not ideal, although I think it really depends. If your cohort is large, you probably don't care if you loose <0.1% of patients. If your cohort is so small that you care, maybe it's worth to dig into this very patient and see if you can trust the data after dataevent 5 (e.g. with checking if the vitals align with the EDW vitals) and do some manual decisions there.
So I think what I might prefer is the tensorizer does not skip the full MRN, if at all the bundles where there's dataevent 5 until next dataevent 1 (if my thoughts from further above are correct) or do not skip anything and rather flag it in the meta-data that there's a dataevent 5 and then the user can decide downstream.

**Comment by RidwanAlam** [comment]
Ok, great. Thanks again @epalto and @wolfgang-ganglberger 

@StevenSong at this point, I think we can continue with the first option that @epalto mentioned: 

>We write all the .mat files and we let the user decide what to do with data containing dataevent 5 by looking at the time_corr_array.

Of course, after incorporating the `bedmaster_indexer` filtering; 
the other options can be implemented downstream by the user, 
also we should highlight the importance of the `time_corr_array` in the documentation, especially in the `TensorMap` section. I believe that's where the downstream implementation will go eventually.

**Comment by erikr** [comment]
> also we should highlight the importance of the `time_corr_array` in the documentation, especially in the `TensorMap` section. I believe that's where the downstream implementation will go eventually.

Good idea. Our current [`TensorMaps`](https://github.com/aguirre-lab/ml4c3/wiki/TensorMaps) does not have much content related to Bedmaster data and could be improved.

Who knows the most about `time_corr_array` that could update our docs ([link to create new issue](https://github.com/aguirre-lab/ml4c3-wiki/issues/new))?
